#
# This is the Docker image that gets published to GitHub.
#
# Goreleaser takes care of building the binary.
#
FROM alpine:3

COPY publiccode-validator-api /usr/local/bin/publiccode-validator-api

ENTRYPOINT ["/usr/local/bin/publiccode-validator-api"]
